version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: registry.gitlab.com/hard-tech/bankys/frontend:latest

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: registry.gitlab.com/hard-tech/bankys/backend:latest
